services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    working_dir: /app
    ports:
      - "3000:3000"
    user: "1010:1010"
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
      - app_next:/app/.next
      - puppeteer_cache:/tmp/puppeteer-cache
      - ./scripts:/app/scripts
      - reports_data:/app/reports
    env_file:
      - .env
    depends_on:
      - db
    environment:
      PUPPETEER_CACHE_DIR: /tmp/puppeteer-cache
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
    command: >
      sh -lc '
        # Next
        [ -x node_modules/.bin/next ] || (npm ci || npm install);

        # Prisma
        npx prisma migrate deploy || true;
        npx prisma generate;

        # Puppeteer
        node -e "const p=require('puppeteer').executablePath(); console.log(p||''); process.exit(p?0:1)" \
          || (mkdir -p /tmp/puppeteer-cache && npx puppeteer browsers install chrome);

        # Start Next dev
        exec npx next dev -H 0.0.0.0 -p 3000
      '

  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_DATABASE: a11y_pulse
      MYSQL_USER: a11y
      MYSQL_PASSWORD: a11y
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data:
  app_node_modules:
  app_next:
  puppeteer_cache:
  reports_data: