services:
  app:
    environment:
      NODE_ENV: production
      PUPPETEER_ARGS: --no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage
      PUPPETEER_CACHE_DIR: /home/nodeapp/.cache/puppeteer
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    working_dir: /app
    ports:
      - "3000:3000"
    user: "1010:1010"
    volumes:
      - app_node_modules:/app/node_modules
      - app_next:/app/.next
      - puppeteer_cache:/home/nodeapp/.cache/puppeteer
      - ./scripts:/app/scripts
      - reports_data:/app/reports
    env_file:
      - .env
    depends_on:
      - db
    shm_size: "1gb"
    command: >
      sh -lc "
        (npm ci || npm install) &&
        npx prisma migrate deploy &&
        npx prisma generate &&
        npm run build &&
        npm run start -p 3000
      "

  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_DATABASE: a11y_pulse
      MYSQL_USER: a11y
      MYSQL_PASSWORD: a11y
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  app_node_modules:
  app_next:
  puppeteer_cache:
  reports_data: