services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    working_dir: /app
    ports:
      - "3000:3000"
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
      - app_next:/app/.next
      - ./scripts:/app/scripts
      - ./reports:/app/reports
    env_file:
      - .env
    depends_on:
      - db
    environment:
      PUPPETEER_CACHE_DIR: /tmp/puppeteer-cache
    command: sh -c "npx prisma generate && npm run dev"

  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_DATABASE: a11y_pulse
      MYSQL_USER: a11y
      MYSQL_PASSWORD: a11y
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data: