name: Deploy to Staging

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          script_stop: true
          script: |
            set -Eeuo pipefail

            cd /var/www/a11y

            git fetch --all
            git reset --hard origin/main

            COMPOSE_BASE="-f docker-compose.prod.yml"

            docker compose $COMPOSE_BASE up -d --build --remove-orphans app
            docker compose $COMPOSE_BASE up -d --wait app || true
            docker image prune -f || true
